### ISSUE TITLE
Unable to Install (Broken Dependency?)

### ISSUE THREAD

**Issue by gionikola** [sboysel/fredr#100]
Hi,

I'm unable to install and load the fredr package in a GitHub Actions job that installs the latest version of R on a machine running the latest version of Ubuntu.

Running `install.packages()` gives the following error: "ERROR: dependency ‘httr’ is not available for package ‘fredr’"

I've tried installing httr separately, but that doesn't seem to work either.

Here's a link to the latest job fail: https://github.com/gionikola/data-reports/actions/runs/2357378203

**Comment by DavisVaughan** [comment]
httr failed to install because curl failed to install. curl failed to install because the GHA worker doesn't have libcurl installed on it. It is here in the error log https://github.com/gionikola/data-reports/runs/6522276501?check_suite_focus=true#step:5:942

You could probably add a DESCRIPTION file to your repo even though it isn't a package, and then use the standard `setup-r-dependencies` action. That uses {pak} and other tools that will install the system dependencies like libcurl for you https://github.com/r-lib/actions/tree/v2-branch/setup-r-dependencies

This isn't a fredr issue though, so ill close

**Comment by gionikola** [comment]
That did the trick -- thank you!
